/* Growth: daily moves toward becoming well read, well spoken and successful. */
window.GROWTH = {
  areas: {
    Read: ["Read 20 pages of a non-fiction book", "Read one long-form article (The Atlantic, Aeon, HBR)", "Read 10 pages of a classic novel", "Read a chapter, then write 3 lines on what it said", "Read one Wikipedia 'featured article' start to finish", "Read the first chapter of a book on your to-read list", "Read an essay by Paul Graham or Morgan Housel", "Read a short story before bed", "Re-read your highlights from a past book", "Read one poem out loud", "Read a biography chapter of someone you admire", "Read 20 pages instead of scrolling tonight"],
    Learn: ["Watch one lecture or TED talk and note 3 takeaways", "Learn how the stock market actually works (15 min)", "Learn one historical event you only half know", "Spend 20 minutes on a free Coursera or Khan Academy lesson", "Learn the basics of one country's culture and history", "Explain a concept you learned this week in 5 sentences", "Look up the origin of a word you use every day", "Learn one rule of grammar you're unsure about", "Learn 10 phrases in a new language", "Study one famous painting and why it matters", "Learn one law of physics in plain English", "Watch a documentary episode instead of a series episode"],
    Skill: ["Spend 30 focused minutes on your most valuable career skill", "Practise Excel or Google Sheets: learn one new formula", "Build or improve one thing for your portfolio", "Rewrite one CV bullet to show a result with a number", "Learn one keyboard shortcut and use it all day", "Do one LinkedIn Learning or YouTube tutorial and apply it", "Practise typing for 10 minutes", "Write a short how-to about something you do well", "Ask for feedback on one piece of your work", "Automate or simplify one task you repeat", "Learn one AI tool that saves you time", "Study a job description for your dream role and list the gaps"],
    Money: ["Track every rupee or dollar you spend today", "Read about index funds for 15 minutes", "Cancel or review one subscription", "Set a savings goal and the amount per week", "Learn what compound interest does to ₹1,000 over 20 years", "Check your bank statement for the last 7 days", "Learn one tax rule that applies to you", "Write down your three money priorities this year", "Compare prices before one purchase today", "Read one chapter of a personal finance book", "Move a small amount into savings today", "Learn what an emergency fund is and how big yours should be"],
    Body: ["Walk 30 minutes without your phone", "Drink 8 glasses of water", "Stretch for 10 minutes", "Sleep before 11 pm", "Eat one extra portion of vegetables", "Do 20 squats and 10 push-ups", "Take the stairs every time today", "Spend 10 minutes in sunlight", "Try a 15-minute yoga video", "No sugar drinks today", "Do a 5-minute breathing exercise", "Prepare tomorrow's healthy lunch tonight"],
    Connect: ["Message one person you admire with a thoughtful question", "Thank a teacher, mentor or friend who helped you", "Comment meaningfully on 3 LinkedIn posts in your field", "Call a family member just to talk", "Introduce two people who should know each other", "Ask someone about their job and really listen", "Reconnect with an old classmate", "Join one online community in your field", "Compliment someone sincerely and specifically", "Ask for one coffee chat this week", "Share something useful you learned with a friend", "Write a kind review for a small business"],
    Speak: ["Record yourself speaking for 2 minutes and listen back", "Write 200 words about anything, then edit it down to 150", "Use today's new word in a conversation", "Practise a 60-second introduction of yourself", "Write a short LinkedIn post about something you learned", "Read an article aloud to work on clear speech", "Summarise a book or video in 3 sentences", "Answer one common interview question out loud", "Write a thank-you email with zero filler words", "Explain your goals to someone in under a minute", "Journal one page in full sentences, no bullet points", "Tell a short story from your week with a beginning, middle and end"],
    Culture: ["Listen to one classical or jazz piece with full attention", "Learn about one famous artist and look at 5 of their works", "Watch a highly rated film from another country", "Read about one philosopher's main idea", "Visit a museum's online collection for 15 minutes", "Cook a dish from a cuisine you've never made", "Learn the story behind a world landmark", "Listen to a podcast episode on history or science", "Read the news from a source in another country", "Learn about one important woman in history", "Explore one architectural style and spot it around you", "Read about one major world religion respectfully and curiously"],
  },
  words: [
    ["Eloquent", "fluent and persuasive in speaking or writing", "Her eloquent answer won the room."], ["Resilient", "able to recover quickly from difficulty", "A resilient mind treats setbacks as lessons."],
    ["Meticulous", "showing great attention to detail", "She kept meticulous notes in her planner."], ["Pragmatic", "dealing with things sensibly and realistically", "Take a pragmatic first step."],
    ["Candid", "truthful and straightforward", "Thank you for the candid feedback."], ["Diligent", "careful and hardworking", "Diligent effort beats talent that rests."],
    ["Ephemeral", "lasting a very short time", "Moods are ephemeral; habits stay."], ["Ubiquitous", "present everywhere", "Phones are ubiquitous, focus is rare."],
    ["Articulate", "able to express ideas clearly", "Be articulate about what you want."], ["Tenacious", "holding firmly to a goal", "A tenacious job search gets results."],
    ["Benevolent", "kind and generous", "Her benevolent leader made time for everyone."], ["Cogent", "clear, logical and convincing", "Make a cogent case for your idea."],
    ["Discerning", "showing good judgement", "Be discerning about what you read."], ["Equanimity", "calmness under pressure", "She met the interview with equanimity."],
    ["Fortitude", "courage in pain or adversity", "Fortitude is quiet and steady."], ["Gregarious", "fond of company, sociable", "A gregarious colleague can open doors."],
    ["Hubris", "excessive pride", "Confidence helps; hubris hurts."], ["Impeccable", "without flaws", "Her timing was impeccable."],
    ["Juxtapose", "place side by side to compare", "Juxtapose your goals with your calendar."], ["Kinetic", "relating to motion", "She had a kinetic, energetic presence."],
    ["Lucid", "clear and easy to understand", "Write lucid emails."], ["Magnanimous", "generous to others, especially rivals", "Be magnanimous in success."],
    ["Nuance", "a subtle difference in meaning", "Good writers notice nuance."], ["Ostensibly", "apparently, but perhaps not actually", "Ostensibly simple, it took weeks."],
    ["Paradigm", "a typical model or pattern", "This job is a paradigm shift for me."], ["Quintessential", "the most perfect example", "The quintessential slow morning."],
    ["Reticent", "not revealing thoughts readily", "She was reticent at first, then brilliant."], ["Sagacious", "wise and showing good judgement", "Ask the most sagacious person you know."],
    ["Tenable", "able to be defended", "Is that plan tenable for a year?"], ["Unprecedented", "never done or known before", "An unprecedented year of growth."],
    ["Venerate", "regard with great respect", "Readers venerate great authors."], ["Wistful", "with a sad longing", "A wistful look at old photos."],
    ["Zealous", "full of energy and enthusiasm", "A zealous learner finishes courses."], ["Acumen", "the ability to make good judgements quickly", "Build your business acumen."],
    ["Bolster", "support or strengthen", "Each win bolsters confidence."], ["Conscientious", "wishing to do one's work well", "A conscientious planner keeps promises."],
    ["Deference", "polite respect", "Listen with deference, speak with confidence."], ["Exemplary", "serving as a desirable model", "Exemplary consistency this week."],
    ["Fastidious", "very attentive to accuracy", "Fastidious about her CV formatting."], ["Gravitas", "dignity and seriousness", "She spoke with quiet gravitas."],
    ["Innate", "inborn, natural", "Curiosity is innate; discipline is learned."], ["Laconic", "using very few words", "A laconic, powerful reply."],
    ["Mitigate", "make less severe", "Planning mitigates stress."], ["Obfuscate", "make unclear", "Don't obfuscate; say it simply."],
    ["Perspicacious", "quick to notice and understand", "A perspicacious reader of people."], ["Serendipity", "a happy accident", "Networking creates serendipity."],
    ["Tacit", "understood without being said", "There was tacit agreement."], ["Verbose", "using more words than needed", "Cut verbose sentences in half."],
    ["Alacrity", "brisk and cheerful readiness", "She accepted the challenge with alacrity."], ["Ameliorate", "make something better", "Small habits ameliorate a hard season."],
    ["Burgeoning", "growing quickly", "Her burgeoning career surprised no one."], ["Catalyst", "something that causes change", "This planner is my catalyst."],
    ["Erudite", "having great knowledge from study", "Daily reading makes you erudite."], ["Indefatigable", "never tiring", "An indefatigable job seeker."],
    ["Poised", "calm and composed; ready", "Poised for the next chapter."], ["Sanguine", "optimistic, especially in difficulty", "Stay sanguine about the search."],
  ],
  ideas: [
    ["Compound interest", "Small gains, repeated, become enormous. 1% better a day is about 37 times better in a year."],
    ["Pareto principle", "About 80% of results come from 20% of efforts. Find your 20% and protect it."],
    ["Circle of competence", "Know what you truly understand, and grow it on purpose."],
    ["First principles", "Break a problem into basic truths and build up from there, instead of copying others."],
    ["Inversion", "Ask what would guarantee failure, then avoid those things."],
    ["Deep work", "Long, undistracted focus produces your most valuable work. Schedule it like a meeting."],
    ["Growth mindset", "Ability grows with effort and strategy. 'Not yet' instead of 'I can't'."],
    ["Opportunity cost", "Every yes is a no to something else. Choose what you give up."],
    ["Second-order thinking", "Ask 'and then what?' to see consequences beyond the first one."],
    ["The Feynman technique", "Explain it simply, find the gaps, study them, explain again."],
    ["Spaced repetition", "Review what you learn at growing intervals and you'll remember it for years."],
    ["Habit stacking", "Attach a new habit to an existing one: after I pour my tea, I read one page."],
    ["Parkinson's law", "Work expands to fill the time you give it. Set shorter deadlines."],
    ["Eisenhower matrix", "Sort tasks by urgent and important. Do, schedule, delegate or drop."],
    ["Sunk cost fallacy", "Past effort isn't a reason to continue. Decide on future value."],
    ["Confirmation bias", "We notice what we already believe. Read people who disagree with you."],
    ["The Dunning–Kruger effect", "Beginners overestimate skill; experts often underestimate it. Stay humble and keep going."],
    ["Leverage", "Code, media, capital and people multiply your effort. Build at least one."],
    ["Lindy effect", "Ideas that have lasted long tend to keep lasting. Read old books."],
    ["Margin of safety", "Leave room for error in money, time and plans."],
    ["Network effects", "Relationships grow in value as they connect. Give before you ask."],
    ["Stoic dichotomy of control", "Focus only on what you can control: your effort, your response."],
    ["Kaizen", "Continuous, tiny improvements beat rare big changes."],
    ["Ikigai", "Look for the overlap of what you love, what you're good at, what the world needs and what pays."],
    ["The 5-second rule", "Count 5-4-3-2-1 and move before your brain talks you out of it."],
    ["Atomic habits", "Make it obvious, attractive, easy and satisfying."],
    ["Zeigarnik effect", "Unfinished tasks nag at us. Write them down to free your mind."],
    ["Halo effect", "One good trait colours how people see everything else. Make first impressions count."],
    ["Occam's razor", "The simplest explanation is usually right. Prefer simple plans too."],
    ["Hanlon's razor", "Don't assume malice where carelessness explains it. It saves energy."],
    ["Regret minimisation", "Picture yourself at 80. Which choice would you regret not making?"],
    ["Comparative advantage", "Spend time where you're relatively strongest, even if others are better at many things."],
    ["Antifragility", "Some things grow stronger from stress. Small challenges make you sturdier."],
    ["The Pygmalion effect", "Higher expectations raise performance. Expect more from yourself, kindly."],
    ["Temporal discounting", "We undervalue future rewards. Make future-you vivid to choose better now."],
    ["Peak-end rule", "We remember experiences by their best moment and their end. End days well."],
    ["Social proof", "People follow what others do. Surround yourself with people who do the hard things."],
    ["Diminishing returns", "After a point, more effort gives less. Know when good is good enough."],
    ["Active recall", "Testing yourself beats re-reading. Close the book and say what you learned."],
    ["Optionality", "Keep doors open cheaply: skills, savings and relationships create options."],
  ],
  habits: [
    ["Read every day", "Twenty pages a day is about 30 books a year. Nothing compounds like reading."],
    ["Keep a learning log", "Write one line about what you learned each day. It turns information into knowledge."],
    ["Learn one new word a day", "A rich vocabulary makes you clearer, more persuasive and more confident."],
    ["Protect a deep-work hour", "One hour without your phone on your most important skill, every weekday."],
    ["Build a portfolio", "Show, don't tell. One project a month makes you stand out to employers."],
    ["Write in public", "A short LinkedIn post a week builds your name and sharpens your thinking."],
    ["Network with generosity", "One thoughtful message a week. Help first, ask later."],
    ["Learn about money early", "Track spending, save automatically and learn the basics of investing."],
    ["Move your body daily", "Exercise improves focus, mood and memory, not just fitness."],
    ["Review your week", "A Sunday review turns busy weeks into deliberate progress."],
    ["Learn a language", "Ten minutes a day opens new cultures, jobs and ways of thinking."],
    ["Sleep like it matters", "Learning is stored during sleep. Seven to eight hours is a success habit."],
  ],
};
